import {
  ArrowLeft,
  AudioLines,
  Banknote,
  BarChart3,
  Bell,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  ClipboardList,
  Clock,
  CloudCheck,
  CreditCard,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Filter,
  GripVertical,
  HardHat,
  Home,
  Hourglass,
  IdCard,
  Image as ImageIcon,
  LayoutDashboard,
  ListChecks,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  Megaphone,
  Menu,
  MessageCircle,
  Mic,
  Moon,
  MoveVertical,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  ReceiptText,
  Search,
  Send,
  ShieldCheck,
  ShowerHead,
  Smartphone,
  Snowflake,
  SprayCan,
  Square,
  Star,
  Sun,
  Trash2,
  Trees,
  TrendingUp,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Waves,
  Wrench,
  X,
  Zap,
} from "lucide-react";

import { cn } from "@/lib/utils";

/** Maps the design's Material Symbol names to lucide icons. */
const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  calendar_month: CalendarDays,
  account_balance_wallet: Wallet,
  handyman: Wrench,
  campaign: Megaphone,
  person: User,
  assignment: ClipboardList,
  apartment: Building2,
  receipt_long: ReceiptText,
  meeting_room: DoorOpen,
  bar_chart: BarChart3,
  checklist: ListChecks,
  logout: LogOut,
  close: X,
  menu: Menu,
  search: Search,
  palette: Palette,
  notifications: Bell,
  light_mode: Sun,
  dark_mode: Moon,
  add: Plus,
  water_drop: Droplet,
  group: Users,
  groups: Users,
  garage: Warehouse,
  payments: Banknote,
  plumbing: ShowerHead,
  bolt: Zap,
  elevator: MoveVertical,
  ac_unit: Snowflake,
  trending_up: TrendingUp,
  schedule: Clock,
  event_available: CalendarCheck,
  event: CalendarClock,
  filter_list: Filter,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  person_add: UserPlus,
  fitness_center: Dumbbell,
  pool: Waves,
  deck: Trees,
  drag_indicator: GripVertical,
  error: CircleAlert,
  check: Check,
  check_circle: CircleCheck,
  arrow_back: ArrowLeft,
  priority_high: TriangleAlert,
  pending_actions: Hourglass,
  task_alt: CircleCheckBig,
  water_damage: Droplets,
  cleaning_services: SprayCan,
  home: Home,
  admin_panel_settings: ShieldCheck,
  engineering: HardHat,
  badge: IdCard,
  smartphone: Smartphone,
  mail: Mail,
  lock: Lock,
  verified_user: ShieldCheck,
  cloud_done: CloudCheck,
  receipt: ReceiptText,
  wallet: Wallet,
  calendar: CalendarDays,
  building: Building2,
  chart: BarChart3,
  "credit-card": CreditCard,
  chat: MessageCircle,
  send: Send,
  mic: Mic,
  stop: Square,
  play: Play,
  pause: Pause,
  edit: Pencil,
  delete: Trash2,
  image: ImageIcon,
  graphic_eq: AudioLines,
  star: Star,
};

interface Props {
  name: string;
  className?: string;
  strokeWidth?: number;
}

export function AppIcon({ name, className, strokeWidth = 1.9 }: Props) {
  const Icon = ICONS[name] ?? CircleAlert;
  return <Icon className={cn("size-5", className)} strokeWidth={strokeWidth} />;
}
